version: '3.9'

services:
  api:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: sales_app
    env_file:
      - ../.env
    ports:
      - "8000:80"
      - "10004:10004"
    environment:
      DEBUGGER: "True"
      POSTGRES_DB: mydatabase
      POSTGRES_HOST: db
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_PORT: 5432
      POSTGRES_USER: myuser
      POSTGRES_MINSIZE: 1
      POSTGRES_MAXSIZE: 10
      JWT_SECRET_KEY: 09d25e094faa6ca2556c818166b7a9563b93f7099f6f0f4caa6cf63b88e8d3e7
    depends_on:
      - db

  db:
    image: postgres:13
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mysecretpassword
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
